# Site settings
title: "" # the name of your site, e.g. ACME Corp.
email:
author:
description:
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
permalink: :title/